In [1]:
# this is a comment

In [3]:
print("this is a comment")

this is a comment


In [1]:
"""Softmax"""

# usamos decimales para que sean autom reales
scores = [3.0, 1.0, 0.2]
print(scores)

[3.0, 1.0, 0.2]


In [2]:
iscores = [3, 1, 0.2]
print(iscores)


[3, 1, 0.2]


In [3]:
# funciones para cambiar de tipo de número no aplican a objeto completo
float(3) 


3.0

In [4]:
float(scores[1]) # ojo que listas comienzan en 0!!!!

1.0

In [5]:
float(scores[0])

3.0

In [6]:
import numpy as np
#import math #NOOOOOOOOOOOOOOOOOOOOOOOO porque se llevan mal numpy y math!!!!!

In [7]:
### NOOOOO hacen falta bucles
# mira respuesta en stackoverflow
# http://stackoverflow.com/questions/34968722/softmax-function-python
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis = 0)

In [8]:
print(scores)

[3.0, 1.0, 0.2]


In [9]:
softmax(scores)

array([ 0.8360188 ,  0.11314284,  0.05083836])

In [10]:
print(softmax(scores))

[ 0.8360188   0.11314284  0.05083836]


In [15]:
scores2 = [x * 2 for x in scores]

In [16]:
print(scores2)

[6.0, 2.0, 0.4]


In [17]:
scores3 = [x / 10 for x in scores]

In [18]:
print(scores3)

[0.3, 0.1, 0.02]


In [19]:
softmax(scores3)

array([ 0.38842275,  0.31801365,  0.2935636 ])

In [ ]:
# aprender funciones
# 1 en bucle hay que poner expresión primero y luego append(expresión)
# 2 ojo a la sintaxis de for


In [81]:
# Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])

In [ ]:
plt.plot(x, softmax(scores).T, linewidth=2)


In [ ]:
plt.show()